### ISSUE TITLE
Blade Ward has the wrong duration

### ISSUE THREAD

**Issue by calculuschild** [ephe/grimoire#101] opened 2015-05-12 18:14 UTC
Duration should be "1 round", not "Concentration, up to 10 minutes"

**Comment by jayrab** [comment] 2015-05-12 19:20
I can confirm this, page 218 of the book it does say 1 round.

**Comment by ephe** [comment] 2015-08-08 02:03
Looks like this got merged in and fixed, so closing as fixed. Thanks all!

**Closed by ephe** 2015-08-08 02:03 UTC
